# Generated by Django 3.1.7 on 2021-03-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='', max_length=70)),
                ('P1', models.CharField(default='', max_length=200)),
                ('P2', models.CharField(default='', max_length=200)),
                ('P3', models.CharField(default='', max_length=200)),
                ('P4', models.CharField(default='', max_length=200)),
                ('P5', models.CharField(default='', max_length=200)),
                ('P6', models.CharField(default='', max_length=200)),
                ('P7', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
